
[[sec-data-product-identification]]
== Measurement Uncertainty in Hydrography

=== Introduction

* Uncertainty is used to support our understanding of the measurements. It's about managing uncertainties.
* The importance of an uncertainty budget (prediction) and estimating the uncertainty from the data (data-driven).
* Contrary to land surveying techniques, the establishment of control points is mostly not feasible in hydrographic surveying. Hence, we cannot use the same metrics to evaluate accuracy of e.g. depth, current speed.
* Accuracy should not be confused with uncertainty
* Introduce the fundamental difference between the uncertain approach and the error approach

=== Fundamentals of Error Theory

* All measurements are fundamentally wrong.
* Describe the concept of an error and its different types (systematic and random). A blunder will not be considered as an error (as based on our definition of error)
* Describe our (hydrographic) understanding of the concepts of accuracy/bias and precision/variance (standard deviation)
* Describe the RMSE as a metric to evaluate both error components (random and systematic) with reference data (i.e. control points)
* Use the preceding explanation as a justification why we need the uncertainty approach in Hydrography and describe it.
* Describe the relevant concepts and terms (adapted to Hydrography from VIM) in the uncertainty approach: uncertainty, 95% confidence level (aka. expanded uncertainty), ways to estimate uncertainty (type A and B evaluations), combining uncertainties.

=== Uncertainty Applied to Hydrographic Surveying

* Hydrography has been a strong proponent of predicting uncertainties a priori by applying the law of uncertainty propagation on a functional (georeferencing) model. This is the predictive approach (see 3.1.1). A priori is to be understood in this context as before any observation/measurements are made.
* A posteriori is likewise to be understood as after all observations/measurements have been made. The uncertainty is estimated from the data. This is the data-driven approach (see 3.1.2).

==== Estimating Depth Uncertainties

* The predictive (3.1.1) and data-driven (3.1.2) approaches are fundamentally different in the sense that the predictive approach will estimate an uncertainty for each sounding measurement while the data-driven approach will estimate the uncertainty at a position/node from a statistical computation from multiple sounding measurements.
* The predictive approach tends to overestimate the uncertainty while the data-driven approach tends to underestimate the uncertainty.

===== Predictive Approach

* Describe TPU and its two components: TVU and THU
* Describe how TVU and THU can be calculated using a rigorous mathematical approach. Cite Hare et al. (1995) as an example.
* Describe how TVU and THU can be calculated using a modelling approach. Give an example of using a Monte-Carlo simulation for ALB (Cblue).

===== Data-driven Approach

* Describe how to estimate uncertainty at a specific position/node. This can amount to either computing the standard error or (as proposed by Calder) to compute the variance of only the observations contributing to the depth estimate at that position/node. Commonly this is referred to as Product Uncertainty and is a useful attribute of a bathymetric grid.
* Describe how crosslines are useful at estimating the uncertainty in the (measurement) sensor frame and are therefore a sensor performance indicator.
* Describe how overlaps between independent survey systems may be used to estimate uncertainty (expressed as a mean square error).

==== Practical Applications of Uncertainty

* Using TPU for grid generation (e.g. CUBE)
* Using TPU as a filter

==== Future Trends in Uncertainty Management
