
[[sec-data-product-identification]]
== Measurement Uncertainty in Hydrography

=== Introduction

* Uncertainty is used to support our understanding of the measurements (start with 3 examples). It's about managing uncertainties, because some aspects can be controlled.
* The importance of an uncertainty budget (prediction) and estimating the uncertainty from the data (data-driven).
* Contrary to land surveying techniques, the establishment of control points is mostly not feasible in hydrographic surveying. Hence, we cannot use the same metrics to evaluate accuracy of e.g. depth, current speed. Principles are the same but evaluation tools are not the same. Often, the error budgets will be smaller on land versus sea because we can better control the measurement factors.
* Accuracy should not be confused with uncertainty. Based on the (new) definition of S-32, Accuracy should be qualitative and be related to bias.

S-44 Edition 5 (IHO, 1998) advocated the general adoption of the term _uncertainty_ instead of _error_ in order to better align with the Guide to the Expression of Uncertainty in Measurement (GUM, 2008). This was reflected for example by the change from _Total Propagated Error_ (TPE) to _Total Progagated Uncertainty_ (TPU). The implications of this adaption are however greater than just a change in terminology. Rather, they warrant a change from a more traditional approach to error estimation (i.e. the Error Approach), in which a clear distinguish is made between random and systematic error estimation. In the recommended Uncertainty Approach, this distinction is not made as the nature of the error may not be subject to categorization. Indeed, an error may, for example, display a random nature in the short-term and a systematic nature in the long-term or vice-versa. Instead, the Uncertainty Approach attempts to assign an interval in which the unknowable true value of a measurement is expected to lie as defined within a particular confidence level, irrespective of the nature of that error (random or systematic).

The rest of this chapter is structured as follows. Section 2 will further describe concepts related to error theory as they should be applied to hydrographic surveying. Section 3 will describe how uncertainty should be applied in practice in hydrographic surveying. More emphasis is placed on depth measurement uncertainty, but it should be recognized that measurement uncertainty also applies to other hydrographic measurand such as surface current and tides.

=== Fundamentals of Error Theory

* [Adail] All measurements are fundamentally wrong.
* Describe the concept of an error and its different types (systematic and random). A blunder will not be considered as an error (as based on our definition of error)
* Describe our (hydrographic) understanding of the concepts of accuracy/bias and precision/variance (standard deviation)
* Describe the RMSE as a metric to evaluate both error components (random and systematic) with reference data (i.e. control points)
* Use the preceding explanation as a justification why we need the uncertainty approach in Hydrography and describe it.
* Describe the relevant concepts and terms (adapted to Hydrography from VIM) in the uncertainty approach: uncertainty, normal (Gaussian) distribution of error, 95% confidence level (aka. "expanded uncertainty" but don't use this term), ways to estimate uncertainty ("type A and B evaluations" but don't use these terms), combining uncertainties.

=== Uncertainty Applied to Hydrographic Surveying

* [Joao Celso] Hydrography has been a strong proponent of predicting uncertainties a priori by applying the law of uncertainty propagation on a functional (georeferencing) model. This is the predictive approach (see 3.1.1). A priori is to be understood in this context as before any observation/measurements are made. Yet, it could also be applied afterwards with better sources uncertainty estimates.
* A posteriori is likewise to be understood as after all observations/measurements have been made. The uncertainty is estimated from the data. This is the data-driven approach (see 3.1.2).
* It's important to mention that "predictive" does not necessarily mean a priori + examples "Data driven" usually means a posteriori. OR should we substitute the hedader "predictive" with something else?

==== Estimating Depth Uncertainties

Estimating depths are inherently uncertain due to a combination of instrument limitations, environmental variability, and processing methods. Understanding and quantifying these uncertainties are essential to ensuring safety of navigation, critical for producing reliable bathymetric products and instrumenting scientific- and engineering decision making. 

The predictive and data-driven approaches are fundamentally different in the sense that the predictive approach will estimate an uncertainty for each sounding measurement while the data-driven approach will estimate the uncertainty from a statistical computation from multiple sounding measurements within an appropriate area or node. Each method has distinct purposes, advantages, and limitations, and they are most effective when used together. 

The predictive approach estimates the uncertain of depth measurements based on the knowledge of system uncertainties, sensor capabilities, and environmental factors. This approach provides per-sounding uncertainty, which is beneficial during acquisition and processing. Since the approach relies on accurate characterization of each source of uncertainty, it tends to conservatively overestimate the combined uncertainty. 

The data-driven approach estimates uncertainty after depth measurements have been acquired, using statistical analysis of the measured depths. Instead of collecting each source of uncertainty, the approach relies on actual measurement dispersion to infer the reliability of depth estimates within areas or nodes. This approach directly reflects the variability of depth measurements and useful when producing bathymetric products. However, it tends to underestimate uncertainty, as it neglects systematic uncertainties which effects all depth measurements. In addition, the data-driven approach requires sufficient data density to produce valid statistical estimates of uncertainty.

===== Predictive Approach

* Describe TPU and its two components: TVU and THU
* Describe how TVU and THU can be calculated using a rigorous mathematical approach. Cite Hare et al. (1995) as an example.
* Describe how TVU and THU can be calculated using a modelling approach. Give an example of using a Monte-Carlo simulation for ALB (Cblue).

===== Data-driven Approach

* Describe how to estimate uncertainty at a specific position/node. 
* There is no standard parameter to calculation standard uncertainty. Examples can be:
   - This can amount to either computing the standard error
   - SDASN (standard deviation along the surface normal)
   - (as proposed by Calder) to compute the variance of only the observations contributing to the depth estimate at that position/node.
* Describe how crosslines are useful at estimating the uncertainty in the (measurement) sensor frame and are therefore a sensor performance indicator. Describe how overlaps between independent survey systems may be used to estimate uncertainty (expressed as a mean square error).

==== Practical Applications of Uncertainty

===== Data Processing

* Using TPU for grid generation (e.g. CUBE)
* Using TPU as a filter in real-time or in post-processing
* See Chapter 8

====== Nautical Products

* Uncertainty can be a contribution to CATZOC
* Used as a quality indicator to disambiguate (criteria decision) between surveys for chart production
* Uncertainty can be the input to the Uncertainty Layer of S-102

==== (Future Trends in Uncertainty Management)

* New methods based on ML
* Possible link to B-13
